sudo: required
dist: trusty
language: node_js
node_js: stable
addons:
  firefox: latest
  apt:
    sources:
    - google-chrome
    packages:
    - google-chrome-stable
before_script:
- npm install web-component-tester
- npm install bower
- export PATH=$PWD/node_modules/.bin:$PATH
- bower install
script:
- xvfb-run wct --skip-plugin sauce
- if [ "${TRAVIS_PULL_REQUEST}" = "false" ]; then wct --skip-plugin local; fi
env:
  global:
  - secure: L5+VFaauAilICy3TSETDcuxM1uVjyGjYsuS7QCxj+feiV60C6eVzKmOML0nmEqVMkx8Ba0CxB+HVmiFoe1TteUNOrpyHhBrJ13oDvQhVMEaSvl+ZPlTRpdR+QF8WPUBx/qWQv/8gpA1e+7Ir0ksQ6nj7i1PxQgCwzVy8jFpnMK2bDAu5bCy0huUmFOaaWbSaZWUY3jHGTidr8i7InN1eotNHfDZ3mT9bKm7WBMNN6CT8ofLXK5C/Wv2Fdn/anPHJf/dr+6Rwoy2eks152OYjrkcfMzUHgzb52fFKSWhn6DDIPuhaTSEq2cEvgCgOUkfuQvAm6rUDnw3+ELQdYOaGDfv+v9SCCwQYpZfLvXNWqxfR9NRbIlmNrRXE4Z2eAzMVbvRNFgJxSKWPEzPoW5sp6QLtu30SCeAq17Tc6KPA0srayHqhp3GLV3fqXbL5S+to/iDPQ1KuCtGUtRnA1D8re1NZGvV3OD0n4jBsrxy7VwcuL3LPEPCjYa7TmSWHAYe7HG7l9vrdZJdOSgh7I2s0+ZANQobOCXRV56lmL8w6TTo0Evwj5XjDwvJB35QQo0F9fYc1hfNSvHinJh/A0hItmuvu/Rdtkkzp/mihqSeNttqV7ly7zX2wCb5h6nG8e31E54SlWe36cPgIA5p/+MiuiniK8mUPvlA23Wi2w3zF4sE=
  - secure: FP4jxFkFtAjV/Rr8VrF6BUCLIPOvdP0kSifNBxQME+LPbvUnIAfvmaavVQcc1RzmjOyOTzyVBntRzPpKSkTu6O4M0Xh+9Lm0X2ayCauzci4hu48Ca+k0K4WnIQ33MDkUOR0/UyjUwHcJNKKZ5Y+rdwINOEgaNL+0P0TzwW01tNspzNrRJxXofUCixyueTurKwvb1iuJjhRDodz2W0ML/0Xx0r996NIMzQmCql4l6LjHrh/0ol3SDL9ljtFzEs6rojXyJDAtRNBmYAsZwF0WPNrTVierKM7I/T9DPGg7ja5UrA+vGlASNKDRcg/zMF3QAwXTkN2hziNJOn2M3g8REZN6mJlTWTEd/x3riu2prpZSrPJYhPJsAus9fzd2y/xlyTYR1tmcLNRdH79N98f3PA60cAdNaO4AgOIt2ZDksCjprSi6Wd1MwjoKrACSA7Atjs4gnlx/wX6OR0m3jgOF5c1pgs63e5e39Nrmr9fQiHFedTdOXRkln1j0rEARfWF0wSrlg27Ar7ywWZnJMdVmzrzT5Uv/zheicOz3W2hpccPEEdyGZygyLPErWC7bJayInXDi95rJWt414p4YPKJ4teqGju+q0iYNoYDGZt14f/4OIevidYWgZVhin+6cg69zWdyaGBdPj3UwKpFxVZ3Q7KUjJ5/5COXYNqgt/NJbvwqE=
